### PR TITLE
Initial tests

### PR DESCRIPTION
**Pull request by abarciauskas-bgse**
Adds initial instructions and scripts for:
* Generating URLs to test from 5 datasets
* Running locust or siege
* Reporting results

### CODE REVIEW

**Review by vincentsarago — APPROVED** [review]
LGTM

**Comment by abarciauskas-bgse** [comment]
Feedback from Sean:
1. Run it on an ec2 instance
2. Run simulation multiple times
3. Add dimensions for the chunks

**Comment by abarciauskas-bgse** [comment]
@sharkinsspatial I have made a few modifications: ensuring the `0/0/0` tile is being tested and added the chunk dimension names to the printed output. I have also opened #11 to report robust results. Let me know if you have other feedback for this PR.

**Comment by abarciauskas-bgse** [comment]
@sharkinsspatial merging so this doesn't get too stale but happy to make modifications.

**Pull request merged**
